#!/bin/sh
set -e
if [ $# -ne 1 ]; then
    echo "usage: $0 version" 1>&2
    exit 1
fi
v=$1
repo=github.com/measurement-kit/measurement-kit
t=measurement-kit-$v.tar.gz
origt=`echo $t | sed "s/-$v/_$v.orig/"`
rm -f $t $t.asc $origt
wget https://$repo/releases/download/v$v/$t
wget https://$repo/releases/download/v$v/$t.asc
gpg2 --verify $t.asc
rm $t.asc
mv $t $origt
