#!/usr/bin/env python

from __future__ import print_function
import re

# measurement-kit (0.2.3-2ubuntu4) xenial; urgency=medium
REGEX = re.compile(r"^measurement-kit \(([0-9.]+)-[0-9a-z]\) [a-z]+; urgency=[a-z]+$")

def main():
    with open("./measurement-kit/debian/changelog", "r") as fp:
        for line in fp:
            line = line.strip()
            match = REGEX.match(line)
            if match:
                print(match.group(1))
                break

if __name__ == "__main__":
    main()
